# fly.toml app configuration file generated for openai-tesla-gpt on 2023-09-29T08:31:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "openai-tesla-gpt"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
